{% set version = "0.1.0" %}

package:
  name: fgmetric
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/fgmetric/fgmetric-{{ version }}.tar.gz
  sha256: 964680a9535dd1754b8cfb7fc450b8982f6b94bba77ecbee3435c9ffb21fd710

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  run_exports:
    - {{ pin_subpackage('fgmetric', max_pin="x.x") }}

requirements:
  host:
    - python >=3.12
    - hatchling
    - pip
  run:
    - python >=3.12
    - pydantic >=2.11.4

test:
  imports:
    - fgmetric
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/fgmetric/
  summary: Type-validated Python models for delimited data files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - msto
